version: "3.9"

services:

  db:
    container_name: project-recurse-db
    image: postgres
    restart: always
    volumes:
      - ./backend/db/data:/var/lib/postgresql/data
    networks:
      - local-network
    ports:
      - 5432:5432
    environment:
      # TODO: Change these to match *your* db settings!
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    extends:
      file: common-services.yml
      service: api
    command: gunicorn ProjectRecurse.wsgi:application --bind unix:/var/sockets/ProjectRecurse.sock
    volumes:
      - ./docker_sockets:/var/sockets
    environment:
      # TODO: Change these to match *your* db settings!
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  apache2:
    container_name: apache2-local
    build:
      context: ./backend/servers/apache2/
    restart: always
    volumes:
      - ./backend/servers/apache2/conf/httpd.prod.conf:/usr/local/apache2/conf/httpd.conf
      - ./backend/servers/apache2/public_html:/var/www/public_html
      - ./backend/api/ProjectRecurse/static:/var/www/projectrecurse/static
      - ./frontend/react/dist:/var/www/projectrecurse/dist
      - ./frontend/react/public:/var/www/projectrecurse/public_html      
      - ./docker_sockets:/var/sockets
    networks:
      - local-network
    ports:
      - 8000:80

  nginx:
    extends:
      file: common-services.yml
      service: nginx
    volumes:
      - ./backend/servers/nginx/conf/nginx.prod.conf:/etc/nginx/nginx.conf
    ports:
      - 8001:80

volumes:
  db:
    driver: local

networks:
  local-network:
    driver: bridge