version: "3.9"

services:
  api:
    container_name: project-recurse-api
    build:
      context: ./backend/api
    command: gunicorn ProjectRecurse.wsgi:application --bind unix:/var/sockets/ProjectRecurse.sock
    volumes:
      - ./docker_sockets:/var/sockets

  apache2:
    container_name: apache2-local
    build:
      context: ./backend/servers/apache2/
    restart: always
    volumes:
      - ./backend/servers/apache2/conf:/usr/local/apache2/conf
      - ./backend/servers/apache2/public_html:/var/www/public_html
      - ./docker_sockets:/var/sockets
    networks:
      - local-network
    ports:
      - 8000:80

  nginx:
    container_name: nginx-test
    build:
      context: ./backend/servers/nginx/
    restart: always
    volumes:
      # - ./conf:/etc/nginx #<-- /etc/nginx needs files already in the container image
      - ./public_html:/var/www/public_html
      - ./docker_sockets:/var/sockets
    networks:
      - local-network
    ports:
      - 8000:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80


volumes:
  db:
    driver: local

networks:
  local-network:
    driver: bridge