version: "3.9"

services:
  nginx:
    container_name: nginx-local
    build:
      context: ./
    restart: always
    volumes:
      # - ./conf:/etc/nginx #<-- this needs other files already in the container image
      - ./public_html:/var/www/public_html
      - ../../docker_sockets:/var/sockets
    networks:
      - local-network
    ports:
      - 8000:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

volumes:
  nginx:
    driver: local

networks:
  local-network:
    driver: bridge