version: "3.9"

services:
  db:
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      # TODO: Change these to match *your* db settings!
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    build:
      context: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    environment:
      # TODO: Change these to match *your* db settings!
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db