version: "3.9"

services:
  apache2:
    container_name: apache2-local
    build:
      context: ./
    restart: always
    volumes:
      - ./conf:/usr/local/apache2/conf
      - ./public_html:/var/www/public_html
      - ../../docker_sockets:/var/sockets
    networks:
      - local-network
    ports:
      - 80:80

volumes:
  apache2:
    driver: local

networks:
  local-network:
    driver: bridge