services:
  next:
    build:
      context: ../..
      dockerfile: backend/next/Dockerfile

    volumes:
      - ../../frontend/next:/app
      - next_node_modules:/app/node_modules

    working_dir: /app

    env_file:
      - ../../frontend/next/.env.local

    extra_hosts:
      - "host.docker.internal:host-gateway"

    command: npm run dev

    ports:
      - "3000:3000"

volumes:
  next_node_modules: